## explore data

In [ ]:
# We always start with a dataset to train on. Let's download the tiny shakespeare dataset
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

In [ ]:
# read it in to inspect it
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()
print("length of dataset in characters: ", len(text))
print(text[:1000])

In [26]:
chars= sorted(list(set(text)))
vocab_size = len(chars)
print("Vocabulary size: ", vocab_size)
print(chars)
char_to_idx = {ch:i for i,ch in enumerate(chars)}
idx_to_char = {i:ch for i,ch in enumerate(chars)}

encode = lambda x: [char_to_idx[ch] for ch in x]
decode = lambda x: ''.join([idx_to_char[i] for i in x])
print("Encoded: ", encode("hello"))
print("Decoded: ", decode(encode("hello")))

Vocabulary size:  65
['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
Encoded:  [46, 43, 50, 50, 53]
Decoded:  hello


In [27]:
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:10])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47])


In [28]:
# split the data into train and test
n= data.shape[0]
train_data = data[:int(0.8*n)]
val_data = data[int(0.8*n):]

In [12]:
block_size =8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [14]:
x= train_data[:block_size]
y= train_data[1:block_size+1]
for t in range(block_size):
    context =x[:t+1]
    target = y[t]
    print(f'when we see {context} we predict {target}')

when we see tensor([18]) we predict 47
when we see tensor([18, 47]) we predict 56
when we see tensor([18, 47, 56]) we predict 57
when we see tensor([18, 47, 56, 57]) we predict 58
when we see tensor([18, 47, 56, 57, 58]) we predict 1
when we see tensor([18, 47, 56, 57, 58,  1]) we predict 15
when we see tensor([18, 47, 56, 57, 58,  1, 15]) we predict 47
when we see tensor([18, 47, 56, 57, 58,  1, 15, 47]) we predict 58


BatchDimension

In [25]:
torch.manual_seed(0)
block_size= 8# sequence length
batch_size = 4# number of sequences in a batch

def get_batch(split):
    # generate sequences of length block_size
    data= train_data if split=='train' else val_data
    ix = torch.randint(len(data)-block_size, (batch_size,))
    x= torch.stack([data[i:i+block_size] for i in ix])
    y= torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x,y

xb,yb= get_batch('train')
print(xb.shape, yb.shape)
print(xb)
print(yb)

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f'when we see {context} we predict {target}')

torch.Size([4, 8]) torch.Size([4, 8])
tensor([[39, 60, 43,  1, 21,  1, 58, 46],
        [ 1, 63, 53, 59,  6,  1, 57, 47],
        [ 1, 54, 56, 53, 59, 42,  1, 46],
        [ 1, 58, 46, 53, 59,  1, 44, 39]])
tensor([[60, 43,  1, 21,  1, 58, 46, 53],
        [63, 53, 59,  6,  1, 57, 47, 56],
        [54, 56, 53, 59, 42,  1, 46, 43],
        [58, 46, 53, 59,  1, 44, 39, 47]])
when we see tensor([39]) we predict 60
when we see tensor([39, 60]) we predict 43
when we see tensor([39, 60, 43]) we predict 1
when we see tensor([39, 60, 43,  1]) we predict 21
when we see tensor([39, 60, 43,  1, 21]) we predict 1
when we see tensor([39, 60, 43,  1, 21,  1]) we predict 58
when we see tensor([39, 60, 43,  1, 21,  1, 58]) we predict 46
when we see tensor([39, 60, 43,  1, 21,  1, 58, 46]) we predict 53
when we see tensor([1]) we predict 63
when we see tensor([ 1, 63]) we predict 53
when we see tensor([ 1, 63, 53]) we predict 59
when we see tensor([ 1, 63, 53, 59]) we predict 6
when we see tensor([ 1, 

## Bigram Model (testing the data with simplest Model)

In [51]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers and C number of classes(characters)
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)

    
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 65])
tensor(4.9475, grad_fn=<NllLossBackward0>)

Sr?qP-QWktXoL&jLDJgOLVz'RIoDqHdhsV&vLLxatjscMpwLERSPyao.qfzs$Ys$zF-w,;eEkzxjgCKFChs!iWW.ObzDnxA Ms$3


In [55]:
optimizer = torch.optim.Adam(m.parameters(), lr=0.01)
batch_size = 32

for i in range(10000):
    xb, yb = get_batch('train')
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    if i % 1000 == 0:
        print(f'iteration {i}, loss = {loss.item()}')

iteration 0, loss = 2.4616758823394775
iteration 1000, loss = 2.3846993446350098
iteration 2000, loss = 2.3376216888427734
iteration 3000, loss = 2.332671880722046
iteration 4000, loss = 2.47920823097229
iteration 5000, loss = 2.392169713973999
iteration 6000, loss = 2.472682476043701
iteration 7000, loss = 2.5612494945526123
iteration 8000, loss = 2.3629305362701416
iteration 9000, loss = 2.537325382232666


In [57]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


RDYowis by, ome mord an, wende!
D:

BO, ffsbat hyouetrso u?
UCERolbr d paninger n.
BETh a oroe the w


## Self Atention Demo

In [60]:
B,T,C = 4,8,2
logits = torch.randn(B,T,C)
logits.shape

torch.Size([4, 8, 2])

In [62]:
# we are doing logits[b,t]= mean_{i<=t} logit[b,i]
logitsbow = torch.zeros(B,T,C)
for b in range(B):
    for t in range(T):
        logitsprev = logits[b,:t+1] # t,C
        logitsbow[b,t] = logitsprev.mean(dim=0)
        
logits[0]


tensor([[ 0.2685,  0.5452],
        [-0.8923, -0.2797],
        [-1.2508, -0.1609],
        [ 0.2853, -0.2369],
        [ 0.8912,  0.0956],
        [ 0.1292, -1.2688],
        [ 0.7083,  0.0457],
        [ 0.3700, -1.2625]])

In [63]:
logitsbow[0]

tensor([[ 0.2685,  0.5452],
        [-0.3119,  0.1328],
        [-0.6249,  0.0349],
        [-0.3973, -0.0331],
        [-0.1396, -0.0073],
        [-0.0948, -0.2176],
        [ 0.0199, -0.1800],
        [ 0.0637, -0.3153]])

In [67]:
# optimizing abovve code with matrix operations
torch.manual_seed(0)
wei= torch.tril(torch.ones(T,T))
wei= wei/wei.sum(dim=1, keepdim=True)
print(wei)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])


In [72]:
logitsbow2= wei@ logits # (B,T,T) @ (B,T,C) -> (B,T,C)
torch.allclose(logitsbow, logitsbow2)
print(logitsbow2[0], logitsbow[0])

tensor([[ 0.2685,  0.5452],
        [-0.3119,  0.1328],
        [-0.6249,  0.0349],
        [-0.3973, -0.0331],
        [-0.1396, -0.0073],
        [-0.0948, -0.2176],
        [ 0.0199, -0.1800],
        [ 0.0637, -0.3153]]) tensor([[ 0.2685,  0.5452],
        [-0.3119,  0.1328],
        [-0.6249,  0.0349],
        [-0.3973, -0.0331],
        [-0.1396, -0.0073],
        [-0.0948, -0.2176],
        [ 0.0199, -0.1800],
        [ 0.0637, -0.3153]])
